# Generated by Django 2.0.5 on 2019-05-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_auto_20190519_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
