# Generated by Django 2.0.4 on 2018-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_auto_20180519_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='profile_pic',
            field=models.ImageField(upload_to='static/uploads/speakers'),
        ),
    ]
