# Generated by Django 2.0.5 on 2019-05-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_speaker_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='remarks',
            new_name='designation',
        ),
    ]
