# Generated by Django 2.0.5 on 2018-07-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_auto_20180519_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='description',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
