# Generated by Django 2.0.5 on 2018-07-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0004_auto_20180724_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='social_media',
            field=models.TextField(default='blank'),
        ),
    ]
