# Generated by Django 2.0.5 on 2018-08-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eventorder',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='eventorder',
            name='event',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='EventOrder',
        ),
    ]
