# Generated by Django 2.0.5 on 2018-08-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = []
