# Generated by Django 2.1.5 on 2019-05-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180822_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eventorder',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='eventorder',
            name='event',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='EventOrder',
        ),
    ]
