# Generated by Django 2.0.5 on 2019-06-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/uploads/team')),
                ('member_type', models.CharField(choices=[('Dir', 'Director, NIT Raipur'), ('HCD', 'Head of Career development'), ('Fclty', 'Faculty Incharge'), ('MNG', 'Manager'), ('HC', 'Head Co-ordinator'), ('OC', 'Overall Co-ordinator'), ('EXEC', 'Executive')], default='EXEC', max_length=5)),
            ],
        ),
    ]
