# Generated by Django 2.0.5 on 2018-07-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('Dir', 'Director, NIT Raipur'), ('HCD', 'Head of Career development'), ('Fclty', 'Faculty Incharge'), ('MNG', 'Manager'), ('HC', 'Head Co-ordinator'), ('OC', 'Overall Co-ordinator'), ('EXEC', 'Executive')], default='EXEC', max_length=5),
        ),
    ]
