# Generated by Django 2.0.5 on 2018-07-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20180715_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='url',
            new_name='profile_url',
        ),
    ]
