# Generated by Django 2.0.5 on 2018-08-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='app1', max_length=256)),
                ('log', models.CharField(max_length=256)),
                ('link', models.URLField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
    ]
