# Generated by Django 2.0.5 on 2018-08-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
