# Generated by Django 2.0.4 on 2018-05-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='name',
            field=models.CharField(default='app1', max_length=256),
        ),
    ]
