# Generated by Django 2.0.5 on 2018-08-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
