# Generated by Django 2.0.5 on 2019-06-06 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('pic', models.ImageField(upload_to='static/uploads/startups')),
                ('contact', models.TextField(blank=True, max_length=13, null=True)),
                ('url', models.URLField(default='https://ecell.nitrr.ac.in')),
                ('founder', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('flag', models.BooleanField(default=False)),
                ('details', models.TextField(default='details coming soon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartupRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appprofile.Profile')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference1', to='startups.Startup')),
            ],
        ),
    ]
