# Generated by Django 2.0.5 on 2018-09-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0004_merge_20180903_1418'),
        ('startups', '0002_auto_20180904_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('preference1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference1', to='startups.Startup')),
                ('preference2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference2', to='startups.Startup')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appprofile.Profile')),
            ],
        ),
    ]
