# Generated by Django 2.0.5 on 2018-09-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0005_auto_20180906_1646'),
        ('startups', '0002_auto_20180904_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appprofile.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='startup',
            name='details',
            field=models.TextField(default='details coming soon'),
        ),
        migrations.AddField(
            model_name='startup',
            name='url',
            field=models.URLField(default='https://ecell.nitrr.ac.in'),
        ),
        migrations.AddField(
            model_name='startupregister',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference1', to='startups.Startup'),
        ),
    ]
