# Generated by Django 2.1 on 2018-09-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_auto_20180904_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='details',
            field=models.TextField(default='details coming soon'),
        ),
    ]
