# Generated by Django 2.0.5 on 2018-09-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_startup_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='url',
            field=models.URLField(default=4),
            preserve_default=False,
        ),
    ]
