# Generated by Django 2.0.4 on 2018-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_auto_20180519_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='pic',
            field=models.ImageField(upload_to='static/uploads/sponsors'),
        ),
    ]
