# Generated by Django 2.0.4 on 2018-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='profile_pic',
            field=models.ImageField(upload_to='static/uploads/mentors'),
        ),
    ]
