# Generated by Django 2.0.5 on 2018-07-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='msg',
            field=models.DateTimeField(),
        ),
    ]
