# Generated by Django 2.0.5 on 2018-07-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180722_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='msg',
            field=models.TextField(),
        ),
    ]
