# Generated by Django 2.0.5 on 2019-06-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca_requests',
            name='screenshot',
            field=models.ImageField(upload_to='static/screenshots/'),
        ),
    ]
