# Generated by Django 2.0.5 on 2018-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0001_initial'),
    ]

    operations = [
        
    ]
