# Generated by Django 2.0.5 on 2018-08-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0002_auto_20180829_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
    ]
