# Generated by Django 2.0.5 on 2018-09-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0003_remove_profile_score'),
    ]

    operations = [
    ]
