# Generated by Django 2.0.5 on 2018-09-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0004_merge_20180903_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('GST', 'Guest'), ('VLT', 'Voluteer'), ('EXE', 'Executive'), ('MNG', 'Manager'), ('HC', 'Head Co-ordinator'), ('OC', 'Overall Co-ordinator'), ('CA', 'Campus Ambassador')], default='GST', max_length=3),
        ),
    ]
