# Generated by Django 2.0.5 on 2019-05-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0005_auto_20180906_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ca_fb_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ca_li_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ca_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ca_tw_score',
            field=models.IntegerField(default=0),
        ),
    ]
