# Generated by Django 2.0.5 on 2018-06-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0005_auto_20180612_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
    ]
