# Generated by Django 2.0.5 on 2018-08-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0006_auto_20180618_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.TextField(blank=True, default='999999999', max_length=12, null=True),
        ),
    ]
