# Generated by Django 2.0.5 on 2019-05-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0006_auto_20190521_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='CA_Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='static/uploads/screenshots')),
                ('social_platform', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('LI', 'LinkedIn')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='ca_requests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='appprofile.CA_Requests'),
        ),
    ]
