# Generated by Django 2.0.5 on 2019-05-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0007_auto_20190521_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ca_requests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='appprofile.CA_Requests'),
        ),
    ]
