# Generated by Django 2.0.5 on 2018-08-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0007_auto_20180807_0622'),
        ('appprofile', '0007_auto_20180806_1843'),
    ]

    operations = [
    ]
