# Generated by Django 2.0.5 on 2018-08-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0008_merge_20180808_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.TextField(blank=True, default='999999999', max_length=12, null=True),
        ),
    ]
