# Generated by Django 2.0.5 on 2019-05-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0008_auto_20190521_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca_requests',
            name='approve_flag',
            field=models.BooleanField(default=False),
        ),
    ]
