# Generated by Django 2.0.5 on 2019-05-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0009_ca_requests_approve_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca_requests',
            name='screenshot',
            field=models.ImageField(upload_to='screenshots/'),
        ),
    ]
