# Generated by Django 2.0.5 on 2019-05-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0010_auto_20190521_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca_requests',
            name='social_platform',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('LI', 'LinkedIn'), ('WP', 'Whatsapp')], max_length=2),
        ),
    ]
