# Generated by Django 2.0.5 on 2019-05-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0011_auto_20190521_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ca_wp_score',
            field=models.IntegerField(default=0),
        ),
    ]
