# Generated by Django 2.0.5 on 2019-05-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0012_profile_ca_wp_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca_requests',
            name='approve_flag',
        ),
        migrations.AddField(
            model_name='ca_requests',
            name='status_flag',
            field=models.IntegerField(default=0),
        ),
    ]
