# Generated by Django 2.0.5 on 2019-05-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0013_auto_20190521_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ca_requests',
        ),
        migrations.AddField(
            model_name='ca_requests',
            name='ca_requests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='appprofile.Profile'),
        ),
    ]
