# Generated by Django 2.0 on 2018-05-21 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appprofile', '0003_auto_20180518_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('meta', models.ImageField(upload_to='static/uploads/question')),
                ('time_limit', models.IntegerField()),
                ('score', models.IntegerField()),
                ('q_type', models.IntegerField()),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questionset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('set_no', models.IntegerField()),
                ('meta', models.ImageField(upload_to='static/uploads/questionset')),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='q_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bquiz.Questionset'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bquiz.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appprofile.Profile'),
        ),
    ]
