# Generated by Django 2.0.5 on 2018-08-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bquiz', '0002_auto_20180818_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
    ]
