# Generated by Django 2.0.5 on 2018-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bquiz', '0003_auto_20180806_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('IMG', 'Image Question'), ('TXT', 'Test Question')], default='TXT', max_length=4),
        ),
    ]
