# Generated by Django 2.0.5 on 2018-08-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bquiz', '0003_auto_20180818_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.IntegerField(),
        ),
    ]
