# Generated by Django 2.0.5 on 2018-08-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bquiz', '0004_auto_20180820_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionacknowledge',
            name='acknowledge_id',
        ),
    ]
