# Generated by Django 2.0.5 on 2018-08-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bquiz', '0005_remove_questionacknowledge_acknowledge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bquiz.Option'),
            preserve_default=False,
        ),
    ]
