# Generated by Django 2.0.5 on 2018-08-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bquiz', '0005_auto_20180807_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=3)),
                ('text', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='meta',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('IMG', 'Image Question'), ('TXT', 'Text Question')], default='TXT', max_length=4),
        ),
    ]
