# Generated by Django 2.0.5 on 2018-08-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bquiz', '0006_auto_20180810_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(choices=[('OFF', 'B-Quiz not active'), ('ANS', 'Answer submitted'), ('NAN', 'Not answered')], max_length=3),
        ),
    ]
