# Generated by Django 2.0.5 on 2018-08-30 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0002_profile_cumulative_score'),
        ('bquiz', '0006_auto_20180820_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appprofile.Profile')),
                ('questionset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bquiz.Questionset')),
            ],
        ),
        migrations.CreateModel(
            name='RightAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bquiz.Question')),
                ('right_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bquiz.Option')),
            ],
        ),
    ]
