# Generated by Django 2.0.5 on 2018-08-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bquiz', '0007_auto_20180810_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
