# Generated by Django 2.0.5 on 2018-09-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bquiz', '0007_auto_20180903_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(max_length=40),
        ),
    ]
