# Generated by Django 2.0.5 on 2018-08-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bquiz', '0008_auto_20180810_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
