# Generated by Django 2.0.5 on 2018-08-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bquiz', '0009_auto_20180810_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(choices=[('OFF', 'B-Quiz not active'), ('ANS', 'Answer submitted'), ('NAN', 'Not answered'), ('ON', 'B-Quiz is live')], max_length=3),
        ),
    ]
